application:
  applicationName: "clientip-task"
  # Common Deployment Values
  deployment:
    envFrom:
    - type: configmap
      name: clientip-task-config
    - type: secret
      name: clientip-task-secret

    # probes definitions
    probes:
      startupProbe:
        failureThreshold: 30
        periodSeconds: 10
        httpGet:
          path: /
          port: web
      readinessProbe:
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
        initialDelaySeconds: 10
        httpGet:
          path: /
          port: web
      livenessProbe:
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
        httpGet:
          path: /
          port: web

  rbac:
    enabled: false

  sync_secrets:
    enabled: false

 # Common Service Values
  service:
    type: ClusterIP
    ports:
    - web: 3000
    ingress_port: 3000
  
# Common Ingress Values
ingress:
  enabled: true
  className: alb
  annotations: 
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  hosts:
    - host: 
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: client-ip-service
              port:
                number: 3000

service:
  type: ClusterIP
  port: 3000

serviceAccount:
  create: false

autoscaling:
  enabled: false



