# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

application:
  deployment:
    replicas: 1

    # Image
    image:
      repository: nginx
      pullPolicy: IfNotPresent
      tag: latest
      

  # ConfigMaps Configurations
  configMap:
    enabled: true
    files:
      - nameSuffix: config
        data:
          DB_HOST: localhost
          DB_NAME: task_db
          DB_PORT: "5432"
          DB_USERNAME: postgres
  
  # Secrets Configurations
  secret:
    enabled: true
    files:
      - nameSuffix: secret
        data:
          DB_PASSWORD: password